version: '3'
services:
  mysqldb:
    image: "mysql"
    container_name: mysqldb
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auction_db
    ports:
      - "3306:3306"
    networks:
      - auction-network
  frontend:
    image: "dolo650/auction-frontend:latest"
    container_name: auction-frontend
    ports:
      - "3000:3000"
    networks:
      - auction-network
  
  auction-spring:
    image: "dolo650/auction-spring:latest"
    ports:
      - "8082:8082"
    networks:
      - auction-network
    depends_on:
      - mysqldb
    container_name: auction-spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/auction_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - /logs:/logs
  
volumes:
  mysql-data:
    driver: local

networks:
  auction-network:
    external: true